# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='ArtProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('workDate', models.DateField()),
                ('requirements', models.CharField(max_length=1000)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('workDate', models.DateField()),
                ('languages', models.CharField(max_length=500)),
                ('requirements', models.CharField(max_length=1000)),
                ('sourceCode', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='programmingimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.ProgrammingProject'),
        ),
        migrations.AddField(
            model_name='artimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.ArtProject'),
        ),
    ]
