# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artproject',
            name='workDate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='programmingproject',
            name='workDate',
            field=models.CharField(max_length=50),
        ),
    ]
